version: 2

models:
  - name: facts_listings
    tests:
      - dbt_utils.equal_rowcount:
          compare_model: ref('listings_stg')
      - equal_sum:
          column_1: price
          compare_to: source('airbnb_raw', 'listings')
          column_2: price
